FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["WeatherApiWrapper/WeatherApiWrapper.csproj", "WeatherApiWrapper/"]
RUN dotnet restore "WeatherApiWrapper/WeatherApiWrapper.csproj"

COPY . .
WORKDIR "/src/WeatherApiWrapper"
RUN dotnet publish "WeatherApiWrapper.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

EXPOSE 8080

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "WeatherApiWrapper.dll"]